name: Sync GitHub Secret to AWS Secrets Manager

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to sync (must match a GitHub secret)'
        required: true
        type: string

jobs:
  sync_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Echo all repository vars (non-sensitive)
        run: |
          echo "All repository vars:"
          echo "$ALLMYVARS"
        env:
          ALLMYVARS: ${{ toJSON(vars) }}
