name: Deploy Existing Image to Lambda

on:
  workflow_dispatch:  # manual trigger or choose your own

jobs:
    deploy:
        name: Deploy to ECR and update Lambda
        runs-on: ubuntu-latest

        steps:

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.SECRET_KEY }}
                  aws-region: us-west-2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              
            - name: Deploy prebuilt image to AWS Lambda
              env:
                AWS_REGION: us-west-2
                FUNCTION_NAME: your-lambda-function-name
                IMAGE_URI: 992382457530.dkr.ecr.us-west-2.amazonaws.com/testing1:latest
              run: |
                aws lambda update-function-code \
                  --function-name $FUNCTION_NAME \
                  --image-uri $IMAGE_URI \
                  --region $AWS_REGION

    
