name: Deploy Existing Image to Lambda

on:
  workflow_dispatch:  # manual trigger or choose your own

jobs:
    deploy:
        name: Deploy to ECR and update Lambda
        runs-on: ubuntu-latest

        steps:

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-west-2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              
            - name: Deploy prebuilt image to AWS Lambda
              env:
                AWS_REGION: us-west-2
                FUNCTION_NAME: testing1
                IMAGE_URI: 992382457530.dkr.ecr.us-west-2.amazonaws.com/testing1:latest
              run: |
                aws lambda create-function \
                  --function-name $FUNCTION_NAME \
                  --package-type Image \
                  --code ImageUri= $IMAGE_URI \
                  --role arn:aws:iam::992382457530:role/hoang \
                  --region us-west-2

    
